In [1]:
from imports import *
from preprocessing_util import get_column_groups, get_transformers
from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline as SkPipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (
    precision_recall_curve, f1_score, average_precision_score,
    classification_report, confusion_matrix, precision_score, recall_score
)
from xgboost import XGBClassifier
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier
import mlflow
import mlflow.sklearn
from mlflow.models import infer_signature

In [2]:
query = "select * from train_data"
train_data = sql_connect(query)
X = train_data.drop(columns=['TARGET'])
y = train_data['TARGET']
imbalance_ratio = round((y == 0).sum() / (y == 1).sum(), 2)
print(f"Imbalance ratio (Good:Bad) = {imbalance_ratio}")
# Specific weight dict for Logistic Regression and Random Forest
weight_dict = {0: 1, 1: imbalance_ratio}
del train_data
X.head()

Connection to SQL Server established successfully.
Connection closed.
Imbalance ratio (Good:Bad) = 11.42

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,DEBT_TO_INCOME,AVERAGE_EXTERNAL_RATING,N_DOCUMENTS_PROVIDED,ADDITIONAL_DOC_PROVIDED,TOT_PREV_APP,APPROVED_RATIO,REFUSED_RATIO,CANCELLED_RATIO,UNUSED_RATIO,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_RATING_CLIENT,YEARS_BIRTH,YEARS_EMPLOYED,YEARS_REGISTRATION,YEARS_ID_PUBLISH,YEARS_LAST_PHONE_CHANGE,ORG_GROUP,OCCUPATION_TYPE_GROUPED,EDUCATION_LEVEL
0,F,0,0,0,0.909091,0.4045,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Single / not married,House / apartment,2,54.91,1.88,25.36,9.68,1.22,Self-Employed,WhiteCollar/Admin,Higher Academic
1,M,0,1,0,5.334971,0.1513,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,26.01,1.14,0.67,5.97,4.41,Self-Employed,Labour/LowSkill,Medium Education
2,F,0,1,0,3.938567,0.3395,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Pensioner,Separated,House / apartment,2,56.44,-0.00,23.97,1.66,3.21,Unknown/Other,NonActive,Medium Education
3,F,0,1,0,2.231920,0.7154,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Widow,House / apartment,2,65.42,6.66,0.94,11.83,-0.00,Unknown/Other,Technical/Skilled,Medium Education
4,F,1,1,0,5.084746,0.2553,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,32.68,3.83,9.24,5.12,1.30,Public Service,WhiteCollar/Admin,Medium Education

In [4]:
query = "select * from test_data"
test_data = sql_connect(query)
X_test = test_data.drop(columns=['TARGET'])
y_test = test_data['TARGET']
del test_data
X.head()

Connection to SQL Server established successfully.
Connection closed.

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,DEBT_TO_INCOME,AVERAGE_EXTERNAL_RATING,N_DOCUMENTS_PROVIDED,ADDITIONAL_DOC_PROVIDED,TOT_PREV_APP,APPROVED_RATIO,REFUSED_RATIO,CANCELLED_RATIO,UNUSED_RATIO,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_RATING_CLIENT,YEARS_BIRTH,YEARS_EMPLOYED,YEARS_REGISTRATION,YEARS_ID_PUBLISH,YEARS_LAST_PHONE_CHANGE,ORG_GROUP,OCCUPATION_TYPE_GROUPED,EDUCATION_LEVEL
0,F,0,0,0,0.909091,0.4045,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Single / not married,House / apartment,2,54.91,1.88,25.36,9.68,1.22,Self-Employed,WhiteCollar/Admin,Higher Academic
1,M,0,1,0,5.334971,0.1513,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,26.01,1.14,0.67,5.97,4.41,Self-Employed,Labour/LowSkill,Medium Education
2,F,0,1,0,3.938567,0.3395,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Pensioner,Separated,House / apartment,2,56.44,-0.00,23.97,1.66,3.21,Unknown/Other,NonActive,Medium Education
3,F,0,1,0,2.231920,0.7154,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Widow,House / apartment,2,65.42,6.66,0.94,11.83,-0.00,Unknown/Other,Technical/Skilled,Medium Education
4,F,1,1,0,5.084746,0.2553,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,32.68,3.83,9.24,5.12,1.30,Public Service,WhiteCollar/Admin,Medium Education

In [5]:
cv_strategy = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [6]:
column_groups = get_column_groups(X)

#### Model Definitions

In [7]:
model_def = [
    # --- Logistic Regression ---
    {
        'name': 'Logistic Regression L1 (Weighted)',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight=weight_dict),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': None,
        'calibrate': False   # No sampler, weight handles imbalance
    },
    {
        'name': 'Logistic Regression L1 with SMOTE',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight=None),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': SMOTE(sampling_strategy='minority', random_state=42),
        'calibrate': False   # SMOTE balances the data, no extra weight needed
    },
    {
        'name': 'Logistic Regression L1 with UnderSampling + Calibration',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight=None),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42),
        'calibrate': True    # Undersamplers distort probabilities — calibrate after
    },

    # --- Random Forest ---
    {
        'name': 'Random Forest (Weighted)',
        'model': RandomForestClassifier(class_weight=weight_dict, random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': None,
        'calibrate': False
    },
    {
        'name': 'Random Forest with SMOTE',
        'model': RandomForestClassifier(class_weight=None, random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': SMOTE(sampling_strategy='minority', random_state=42),
        'calibrate': False   # SMOTE keeps probabilities stable
    },
    {
        'name': 'Random Forest with UnderSampling + Calibration',
        'model': RandomForestClassifier(class_weight=None, random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42),
        'calibrate': True    # Undersamplers distort probabilities — calibrate after
    },

    # --- XGBoost ---
    {
        'name': 'XGBoost with scale_pos_weight',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss', scale_pos_weight=imbalance_ratio),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': None,
        'calibrate': False
    },
    {
        'name': 'XGBoost with SMOTE',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': SMOTE(sampling_strategy='minority', random_state=42),
        'calibrate': False
    },
    {
        'name': 'XGBoost with UnderSampling + Calibration',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42),
        'calibrate': True    # Undersamplers distort probabilities — calibrate after
    },
]

In [12]:
from sklearn.calibration import CalibratedClassifierCV

mlflow.set_experiment("Credit Risk Modelling Project v6")
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

for i in range(len(model_def)):
    print(f"\nTraining model: {model_def[i]['name']}")
    
    # Select correct transformer type
    model_type = 'linear' if "Regression" in model_def[i]['name'] else 'tree'
    transformers = get_transformers(
        column_groups['log_col'],
        column_groups['scale_only_cols'],
        column_groups['categorical_cols'],
        column_groups['binary_cols'],
        model_type
    )

    # Build pipeline steps (sampler comes before model)
    steps = [('transformer', ColumnTransformer(transformers))]
    if model_def[i]['sampler'] is not None:
        steps.append(('sampler', model_def[i]['sampler']))
    steps.append(('model', model_def[i]['model']))
    pipeline = ImbPipeline(steps)

    random_search = RandomizedSearchCV(
        estimator=pipeline,
        param_distributions=model_def[i]['param_grid'],
        n_iter=5,
        scoring="average_precision",
        cv=cv_strategy,
        n_jobs=-1,
        random_state=42
    )

   
    
    with mlflow.start_run(run_name=model_def[i]['name']) as run:
        random_search.fit(X, y)
        best_model = random_search.best_estimator_

        # ── Calibration (only for Undersampled models) ──────────────────────
        if model_def[i].get('calibrate', False):
            print(f"  Calibrating {model_def[i]['name']} ...")
            calibrated = CalibratedClassifierCV(estimator=best_model, method='isotonic', cv=3)
            calibrated.fit(X, y)
            best_model = calibrated

        signature = infer_signature(X_test, best_model.predict(X_test))

        # ── Train metrics ────────────────────────────────────────────────────
        y_prob = best_model.predict_proba(X)[:, 1]
        precision, recall, thresholds = precision_recall_curve(y, y_prob)
        ap_score = average_precision_score(y, y_prob)
        f1_curve = 2 * (precision * recall) / (precision + recall + 1e-10)
        f1_threshold = thresholds[np.argmax(f1_curve)]
        y_pred = (y_prob >= f1_threshold).astype(int)

        report_df = pd.DataFrame(classification_report(y, y_pred, output_dict=True)).transpose()
        report_df.to_csv("classification_report.csv")
        pd.DataFrame(confusion_matrix(y, y_pred)).to_csv("confusion_matrix.csv")
        pd.DataFrame({'y_true': y, 'y_pred': y_pred, 'y_proba': y_prob}).to_csv("predictions.csv", index=False)

        # ── Test metrics ──────────────────────────────────────────────────────
        y_test_prob = best_model.predict_proba(X_test)[:, 1]
        y_test_pred = (y_test_prob >= f1_threshold).astype(int)

        # ── MLflow logging ───────────────────────────────────────────────────
        mlflow.log_params(random_search.best_params_)
        mlflow.log_param("calibrated", model_def[i].get('calibrate', False))
        mlflow.log_metric("train_precision", precision_score(y, y_pred))
        mlflow.log_metric("train_recall", recall_score(y, y_pred))
        mlflow.log_metric("train_f1", f1_score(y, y_pred))
        mlflow.log_metric("train_avg_precision",   ap_score)
        mlflow.log_metric("f1_threshold",              f1_threshold)
        mlflow.log_metric("test_precision",            precision_score(y_test, y_test_pred))
        mlflow.log_metric("test_recall",               recall_score(y_test, y_test_pred))
        mlflow.log_metric("test_f1",                   f1_score(y_test, y_test_pred))
        mlflow.log_metric("test_avg_precision",        average_precision_score(y_test, y_test_prob))

        mlflow.log_artifact("classification_report.csv")
        mlflow.log_artifact("confusion_matrix.csv")
        mlflow.log_artifact("predictions.csv")
        mlflow.sklearn.log_model(
            best_model, 
            "model", 
            registered_model_name="Credit Risk Model v6"
        )

        print(f"  Done: {model_def[i]['name']} logged.")

2026/02/19 20:10:42 INFO mlflow.tracking.fluent: Experiment with name 'Credit Risk Modelling Project v6' does not exist. Creating a new experiment.

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Training model: Logistic Regression L1 (Weighted)

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:12:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:12:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'Credit Risk Model v6'.
2026/02/19 20:12:45 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 1
Created version '1' of model 'Credit Risk Model v6'.

  Done: Logistic Regression L1 (Weighted) logged.
🏃 View run Logistic Regression L1 (Weighted) at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/93cc1b3f766442dd857fd2eef83b61cc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: Logistic Regression L1 with SMOTE

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:17:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:17:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:17:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 2
Created version '2' of model 'Credit Risk Model v6'.

  Done: Logistic Regression L1 with SMOTE logged.
🏃 View run Logistic Regression L1 with SMOTE at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/ac3717aeceb1482fbdcae9d439d525fe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: Logistic Regression L1 with UnderSampling + Calibration

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

  Calibrating Logistic Regression L1 with UnderSampling + Calibration ...

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:17:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:17:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:17:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 3
Created version '3' of model 'Credit Risk Model v6'.

  Done: Logistic Regression L1 with UnderSampling + Calibration logged.
🏃 View run Logistic Regression L1 with UnderSampling + Calibration at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/3a4b156ab30c4ac3b48edd964fe15ea0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: Random Forest (Weighted)

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:18:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:18:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:18:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 4
Created version '4' of model 'Credit Risk Model v6'.

  Done: Random Forest (Weighted) logged.
🏃 View run Random Forest (Weighted) at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/d89350a6af454b2e98a5bddfb2bd1f98
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: Random Forest with SMOTE

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:19:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:19:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:19:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 5
Created version '5' of model 'Credit Risk Model v6'.

  Done: Random Forest with SMOTE logged.
🏃 View run Random Forest with SMOTE at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/d3a90b5c83a944128f54cf0ddf2094a2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: Random Forest with UnderSampling + Calibration
  Calibrating Random Forest with UnderSampling + Calibration ...

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:19:48 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:19:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:19:54 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 6
Created version '6' of model 'Credit Risk Model v6'.

  Done: Random Forest with UnderSampling + Calibration logged.
🏃 View run Random Forest with UnderSampling + Calibration at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/c34438a0bcc547bcbcceeece377182b5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: XGBoost with scale_pos_weight

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:20:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:20:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:20:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 7
Created version '7' of model 'Credit Risk Model v6'.

  Done: XGBoost with scale_pos_weight logged.
🏃 View run XGBoost with scale_pos_weight at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/dc1fa0f8662a409e9ae7165566126b4b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: XGBoost with SMOTE

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:20:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:20:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:20:48 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 8
Created version '8' of model 'Credit Risk Model v6'.

  Done: XGBoost with SMOTE logged.
🏃 View run XGBoost with SMOTE at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/9ce3e99ffcd0479fbe508264fbed9e99
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

Training model: XGBoost with UnderSampling + Calibration

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

  Calibrating XGBoost with UnderSampling + Calibration ...

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:20:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/02/19 20:20:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/19 20:21:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Credit Risk Model v6' already exists. Creating a new version of this model...
2026/02/19 20:21:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model v6, version 9
Created version '9' of model 'Credit Risk Model v6'.

  Done: XGBoost with UnderSampling + Calibration logged.
🏃 View run XGBoost with UnderSampling + Calibration at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/3f8a747ee978496280c886282fadf4ae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947

## XGBoost model is selectted again and training again with correction in pipeline

In [13]:
from sklearn.metrics import recall_score, precision_score, f1_score, average_precision_score

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Credit Risk Modelling Project v6")

with mlflow.start_run(run_name="XGBoost(Final_Production)"):
    # 1. Log parameters
    xgb_params = {
        "learning_rate": 0.1,
        "max_depth": 3,
        "n_estimators": 50,
        "subsample": 1.0,
        "random_state": 42
    }
    mlflow.log_params(xgb_params)

    # 2. Build Pipeline
    transformers = get_transformers(
        column_groups['log_col'],
        column_groups['scale_only_cols'],
        column_groups['categorical_cols'],
        column_groups['binary_cols'],
        'tree'
    )

    pipeline = ImbPipeline([
        ('transformer', ColumnTransformer(transformers)),
        ('sampler', RandomUnderSampler(sampling_strategy='majority', random_state=42)),
        ('model', XGBClassifier(**xgb_params))
    ])

    # 3. Fit
    pipeline.fit(X, y)

    # 4. Evaluate on Held-out X_test
    y_test_prob = pipeline.predict_proba(X_test)[:, 1]
    y_test_pred = pipeline.predict(X_test)

    mlflow.log_metric("test_recall",        recall_score(y_test, y_test_pred))
    mlflow.log_metric("test_precision",     precision_score(y_test, y_test_pred))
    mlflow.log_metric("test_f1",            f1_score(y_test, y_test_pred))
    mlflow.log_metric("test_avg_precision", average_precision_score(y_test, y_test_prob))

    # 5. Log Model (Use a clean versioned name)
    mlflow.sklearn.log_model(
        pipeline, 
        "model", 
        registered_model_name="Credit Risk Model Final"
    )
    
    print("Final Model Training & Registration Complete.")

2026/02/20 01:05:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/20 01:06:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'Credit Risk Model Final'.
2026/02/20 01:06:47 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Credit Risk Model Final, version 1
Created version '1' of model 'Credit Risk Model Final'.

Final Model Training & Registration Complete.
🏃 View run XGBoost(Final_Production) at: http://127.0.0.1:5000/#/experiments/286339840280967947/runs/bf5578944c124f0381a936c2f9107bd1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/286339840280967947