In [13]:
from imports import *
from preprocessing_util import get_column_groups, get_transformers
from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline as SkPipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (
    precision_recall_curve, f1_score, average_precision_score,
    classification_report, confusion_matrix, precision_score, recall_score
)
from xgboost import XGBClassifier
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier
import mlflow
import mlflow.sklearn

In [2]:
query = "select * from train_data"
train_data = sql_connect(query)
X = train_data.drop(columns=['TARGET'])
y = train_data['TARGET']
del train_data
X.head()

Connection to SQL Server established successfully.
Connection closed.

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,DEBT_TO_INCOME,AVERAGE_EXTERNAL_RATING,N_DOCUMENTS_PROVIDED,ADDITIONAL_DOC_PROVIDED,TOT_PREV_APP,APPROVED_RATIO,REFUSED_RATIO,CANCELLED_RATIO,UNUSED_RATIO,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_RATING_CLIENT,YEARS_BIRTH,YEARS_EMPLOYED,YEARS_REGISTRATION,YEARS_ID_PUBLISH,YEARS_LAST_PHONE_CHANGE,ORG_GROUP,OCCUPATION_TYPE_GROUPED,EDUCATION_LEVEL
0,F,0,0,0,0.909091,0.4045,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Single / not married,House / apartment,2,54.91,1.88,25.36,9.68,1.22,Self-Employed,WhiteCollar/Admin,Higher Academic
1,M,0,1,0,5.334971,0.1513,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,26.01,1.14,0.67,5.97,4.41,Self-Employed,Labour/LowSkill,Medium Education
2,F,0,1,0,3.938567,0.3395,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Pensioner,Separated,House / apartment,2,56.44,-0.00,23.97,1.66,3.21,Unknown/Other,NonActive,Medium Education
3,F,0,1,0,2.231920,0.7154,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Widow,House / apartment,2,65.42,6.66,0.94,11.83,-0.00,Unknown/Other,Technical/Skilled,Medium Education
4,F,1,1,0,5.084746,0.2553,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,32.68,3.83,9.24,5.12,1.30,Public Service,WhiteCollar/Admin,Medium Education

In [3]:
query = "select * from test_data"
test_data = sql_connect(query)
X_test = test_data.drop(columns=['TARGET'])
y_test = test_data['TARGET']
del test_data
X.head()

Connection to SQL Server established successfully.
Connection closed.

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,DEBT_TO_INCOME,AVERAGE_EXTERNAL_RATING,N_DOCUMENTS_PROVIDED,ADDITIONAL_DOC_PROVIDED,TOT_PREV_APP,APPROVED_RATIO,REFUSED_RATIO,CANCELLED_RATIO,UNUSED_RATIO,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_RATING_CLIENT,YEARS_BIRTH,YEARS_EMPLOYED,YEARS_REGISTRATION,YEARS_ID_PUBLISH,YEARS_LAST_PHONE_CHANGE,ORG_GROUP,OCCUPATION_TYPE_GROUPED,EDUCATION_LEVEL
0,F,0,0,0,0.909091,0.4045,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Single / not married,House / apartment,2,54.91,1.88,25.36,9.68,1.22,Self-Employed,WhiteCollar/Admin,Higher Academic
1,M,0,1,0,5.334971,0.1513,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,26.01,1.14,0.67,5.97,4.41,Self-Employed,Labour/LowSkill,Medium Education
2,F,0,1,0,3.938567,0.3395,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Pensioner,Separated,House / apartment,2,56.44,-0.00,23.97,1.66,3.21,Unknown/Other,NonActive,Medium Education
3,F,0,1,0,2.231920,0.7154,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Widow,House / apartment,2,65.42,6.66,0.94,11.83,-0.00,Unknown/Other,Technical/Skilled,Medium Education
4,F,1,1,0,5.084746,0.2553,1,True,0,0.0,0.0,0.0,0.0,Unaccompanied,Working,Married,House / apartment,2,32.68,3.83,9.24,5.12,1.30,Public Service,WhiteCollar/Admin,Medium Education

In [4]:
cv_strategy = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [5]:
column_groups = get_column_groups(X)

#### Model Definitions

In [6]:
model_def = [
    {
        'name': 'Logistic Regression L1',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight='balanced'),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': None
    },
    {
        'name': 'Logistic Regression L1 with SMOTE',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight='balanced'),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': SMOTE(sampling_strategy='minority', random_state=42)
    },
    {
        'name': 'Logistic Regression L1 with UnderSampling',
        'model': LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear', class_weight='balanced'),
        'param_grid': {'model__C': [0.01, 0.1, 1]},
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42)
    },
    {
        'name': 'Random Forest',
        'model': RandomForestClassifier(class_weight='balanced', random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': None
    },
    {
        'name': 'Random Forest with SMOTE',
        'model': RandomForestClassifier(class_weight='balanced', random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': SMOTE(sampling_strategy='minority', random_state=42)
    },
    {
        'name': 'Random Forest with UnderSampling',
        'model': RandomForestClassifier(class_weight='balanced', random_state=42),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [None, 10, 20],
            'model__min_samples_split': [2, 5, 10],
            'model__min_samples_leaf': [1, 2, 4]
        },
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42)
    },
    {
        'name': 'XGBoost',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': None
    },
    {
        'name': 'XGBoost with SMOTE',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': SMOTE(sampling_strategy='minority', random_state=42)
    },
    {
        'name': 'XGBoost with UnderSampling',
        'model': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'param_grid': {
            'model__n_estimators': [50, 100, 200],
            'model__max_depth': [3, 5, 7],
            'model__learning_rate': [0.01, 0.1, 0.2],
            'model__subsample': [0.8, 1.0]
        },
        'sampler': RandomUnderSampler(sampling_strategy='majority', random_state=42)
    }
]

In [14]:
mlflow.set_experiment("Credit Risk Modelling Project")
mlflow.set_tracking_uri("http://127.0.0.1:5000/") 

for i in range(len(model_def)):
    print(f"Training model : {model_def[i]['name']}")
    if "Regression" in model_def[i]['name']:
        transformers = get_transformers(
            column_groups['log_col'],
            column_groups['scale_only_cols'],
            column_groups['categorical_cols'],
            column_groups['binary_cols'],
            'linear'
        )

    else:
        transformers = get_transformers(
            column_groups['log_col'],
            column_groups['scale_only_cols'],
            column_groups['categorical_cols'],
            column_groups['binary_cols'],
            'tree'
        )

    if model_def[i]['sampler'] is not None:
        pipeline = ImbPipeline([
            ('transformer', ColumnTransformer(transformers)),
            ('sampler', model_def[i]['sampler']),
            ('model', model_def[i]['model'])
        ])
    else:
        pipeline = SkPipeline([
            ('transformer', ColumnTransformer(transformers)),
            ('model', model_def[i]['model'])
        ])

    random_search = RandomizedSearchCV(
        estimator=pipeline,
        param_distributions=model_def[i]['param_grid'],
        n_iter=5,  
        scoring="average_precision",
        cv=cv_strategy,
        n_jobs=-1,
        random_state=42
    )
    
    with mlflow.start_run(run_name=model_def[i]['name']) as run:
        
        random_search.fit(X, y)
        best_model = random_search.best_estimator_
        
        y_prob = best_model.predict_proba(X)[:, 1]
        
        precision, recall, thresholds = precision_recall_curve(y, y_prob)
        ap_score  = average_precision_score(y, y_prob)

        f1_curve = 2 * (precision * recall) / (precision + recall + 1e-10)
        f1_score_max = np.max(f1_curve)
        f1_threshold = thresholds[np.argmax(f1_curve)]

        y_pred = (y_prob >= f1_threshold).astype(int)

        report = classification_report(y, y_pred, output_dict=True)
        report_df = pd.DataFrame(report).transpose()
        report_df.to_csv("classification_report.csv")

        cm = confusion_matrix(y, y_pred)
        cm_df = pd.DataFrame(cm)
        cm_df.to_csv("confusion_matrix.csv")

        preds_df = pd.DataFrame({'y_true': y, 'y_pred': y_pred, 'y_proba': y_prob})
        preds_df.to_csv("predictions.csv", index=False)

        # Log model hyperparameters and metrics
        mlflow.log_params(random_search.best_params_)
        mlflow.log_metric("average_precision_score", ap_score)
        mlflow.log_metric("f1_score_max", f1_score_max)
        mlflow.log_metric("f1_threshold", f1_threshold)

        # Log artifacts
        mlflow.log_artifact("classification_report.csv")
        mlflow.log_artifact("confusion_matrix.csv") 
        mlflow.log_artifact("predictions.csv")

        # Log the model
        mlflow.sklearn.log_model(best_model, "model")

        print(f"Model {model_def[i]['name']} trained and logged successfully.")

        # ===== LOG TEST METRICS TO MLFLOW =====

        y_test_prob = best_model.predict_proba(X_test)[:, 1]
        y_test_pred = (y_test_prob >= f1_threshold).astype(int) 

        test_precision = precision_score(y_test, y_test_pred)
        test_recall = recall_score(y_test, y_test_pred)
        test_f1 = f1_score(y_test, y_test_pred)
        test_avg_precision = average_precision_score(y_test, y_test_prob)

        mlflow.log_metric("test_precision", test_precision)
        mlflow.log_metric("test_recall", test_recall)
        mlflow.log_metric("test_f1", test_f1)
        mlflow.log_metric("test_avg_precision", test_avg_precision)

        report_test = classification_report(y_test, y_test_pred, output_dict=True)
        pd.DataFrame(report_test).transpose().to_csv("classification_report_test.csv")
        mlflow.log_artifact("classification_report_test.csv")

        cm_test = confusion_matrix(y_test, y_test_pred)
        pd.DataFrame(cm_test).to_csv("confusion_matrix_test.csv")
        mlflow.log_artifact("confusion_matrix_test.csv")

        preds_test_df = pd.DataFrame({'y_true': y_test, 'y_pred': y_test_pred, 'y_proba': y_test_prob})
        preds_test_df.to_csv("predictions_test.csv", index=False)
        mlflow.log_artifact("predictions_test.csv")

        print("Test metrics and artifacts logged.")

Training model : Logistic Regression L1

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
2025/06/28 20:02:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:02:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Logistic Regression L1 trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Logistic Regression L1 at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/e8328f6437664e6e85c940721a15284e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : Logistic Regression L1 with SMOTE

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
2025/06/28 20:04:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:04:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Logistic Regression L1 with SMOTE trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Logistic Regression L1 with SMOTE at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/92fbb83a4c084fa497ddf6ce8b15b921
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : Logistic Regression L1 with UnderSampling

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=5. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
2025/06/28 20:04:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:04:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Logistic Regression L1 with UnderSampling trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Logistic Regression L1 with UnderSampling at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/9cd2fd30aba64c4db775f7817612f2e8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : Random Forest

2025/06/28 20:05:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:05:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Random Forest trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/6a7808c4ca9d48038d8836082b494c42
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : Random Forest with SMOTE

2025/06/28 20:06:48 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:06:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Random Forest with SMOTE trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Random Forest with SMOTE at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/7eb4a593504045e598e0b10870e4c969
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : Random Forest with UnderSampling

2025/06/28 20:07:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:07:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model Random Forest with UnderSampling trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run Random Forest with UnderSampling at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/a8384880f0cf45c89d89f89e1bdfc1b0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : XGBoost

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:07:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/06/28 20:07:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:07:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model XGBoost trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run XGBoost at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/92d53e7968774c22874774097b45577c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : XGBoost with SMOTE

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:07:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/06/28 20:07:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:07:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model XGBoost with SMOTE trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run XGBoost with SMOTE at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/7e114ad7ac9f48ef89ed3c0bfcdd9e51
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468
Training model : XGBoost with UnderSampling

c:\Users\adars\Documents\Ireland_Project\Loan_approval_ml\loan_approval_env\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:07:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/06/28 20:07:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/06/28 20:07:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Model XGBoost with UnderSampling trained and logged successfully.
Test metrics and artifacts logged.
🏃 View run XGBoost with UnderSampling at: http://127.0.0.1:5000/#/experiments/330911126081939468/runs/d1f667c8a0974e11b75013d2f36215bf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/330911126081939468